export const FETCH_USER = "fetch_user";
export const FETCH_ONEUSER = "fetch_oneuser"
export const UPDATE_USER= "update_user"
export const FETCH_CARS = "fecth_cars";
export const FETCH_ONECAR = "fetch_onecar";
export const FETCH_PURCH = "fetch_purch"
export const UPDATE_ONECAR = "update_car";
export const DELETE_ONECAR = "delete_onecar";
export const ADD_PURCHASE = "add_purchase"
